#!/usr/bin/python
#
# This file is part of trackit.
#
# trackit is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# trackit is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with trackit.  If not, see <http://www.gnu.org/licenses/>.

import Pyro4

VERSION = 0.1

class TracKitDaemon(object):
	def get_fortune(self, name):
		return "Hello, {0}. Here is your fortune message:\n" \
			"Behold the warranty -- the bold print giveth and the fine print taketh away.".format(name)


if __name__ == "__main__":
	trackit     = TracKitDaemon()
	pyro_daemon = Pyro4.Daemon(host='localhost',port=18)
	uri         = pyro_daemon.register(trackit,'trackit-daemon')
	print 'Starting TrackIt daemon version ' + str(VERSION) + '. Client URI: ' + str(uri) 
	pyro_daemon.requestLoop()